### ISSUE TITLE
Suggestion: add other languages

### ISSUE THREAD

**Issue by Hangovers** [jefflomacy/villagerdb#103]
Doing a wish/"what i've got" list is 10 times harder when your game is in a different language from english. Don't know how much time consuming it is but if possible adding the other languages would be fantastic.

**Comment by maxlefou** [comment]
I'm ready to make the french translations of it if needed, once it's implemented.

**Comment by kkslider-dev** [comment]
I'm working on mapping languages for all items using different sources. I've started with an old mapping I had for acnl and I'm also going to do the mapping from this repo [alexislours/acnh-translations](https://github.com/alexislours/acnh-translations)

Follow  https://github.com/jefflomacy/villagerdb/pull/159 to be updated

**Comment by trundleroo** [comment]
Closing this as #159 will be the main issue for localization discussion.
