### ISSUE TITLE
Feature Request: Display "Customizable" indicator in item details

### ISSUE THREAD

**Issue by Avalai** [jefflomacy/villagerdb#107]
Some NH items have a `customizable` property in their JSON. It would be great to make use of this field on the item details page.

The customization options will be listed as color variations, so the `customizable` property is useful to indicate how the other colors can be obtained.

Example item data: [Accessories Stand](https://github.com/jefflomacy/villagerdb/blob/master/data/items/accessories-stand.json)

**Comment by trundleroo** [comment]
This was implemented a little while ago, closing.
