### ISSUE TITLE
Suggestion: Support for asset variants

### ISSUE THREAD

**Issue by DungeonMaestro** [jefflomacy/villagerdb#108]
In Animal Crossing: New Horizons, there are many obtainable furniture and apparel assets which have color variants, such as the Lamp Post, Wooden Table, or Biker Jacket. 

It would be useful as a user to have the ability to track collected or desired variants on the web app using lists, and to describe how variants are obtained (purchase or AC:NH's customization mechanic)

**Comment by trundleroo** [comment]
This is already a work in process and duplication of #93, so I'm closing this!

**Comment by DungeonMaestro** [comment]
Completely overlooked that one, my b
