### ISSUE TITLE
Request — confirmation on delete of list / ability to edit list name

### ISSUE THREAD

**Issue by laurenor** [jefflomacy/villagerdb#126]
I could also submit a PR to make a quick confirmation — basic or stylized in a reusable component — or help in other areas. LMK, thanks!

**Comment by arkamedus** [comment]
Agreed, actions that are destructive should always have a confirmation.

**Comment by trundleroo** [comment]
Renaming lists is covered in #99 however I won't close this issue as it could be used for the confirmation of deleting a list. @laurenor you are more than welcome to submit a PR for this.
