### ISSUE TITLE
Suggestion: Ability to use up/down arrow keys to select option from the search bar

### ISSUE THREAD

**Issue by MinceMeringue** [jefflomacy/villagerdb#139]
When adding my entire catalogue, I noticed it was a tad bit of an annoyance to not be able to type in an item in the search bar and use the down/up arrow keys to select the item and press enter to search for it. 

It's very minor, but just an idea that could save a small amount of time for when people have hundreds of items to add to their catalogues.

Thanks! 👍

**Comment by jefflomacy** [comment]
This was deployed this morning!
