### ISSUE TITLE
Add stripes to item lists for increased readability 

### ISSUE THREAD

**Issue by lacarmen** [jefflomacy/villagerdb#155]
It's a little difficult to line up the delete buttons on my 27" monitor... :) 

![image](https://user-images.githubusercontent.com/8739864/80005313-66521080-8491-11ea-8430-f92c34e80c6f.png)

This could be done by adding a class (such as `item-list`) [here](https://github.com/jefflomacy/villagerdb/blob/master/views/list.hbs#L26) and the following css:

```
.list-group.item-list .list-group-item:nth-child(2n+1) {
    background-color: #eee;
}
```

**Comment by trundleroo** [comment]
Closed by #166
