### ISSUE TITLE
Three furniture corrections

### ISSUE THREAD

**Issue by celynwalters** [jefflomacy/villagerdb#161]
Hi, I found these which may need to be updated:

1. World map is missing customisation, options are `Pacific Ocean` and `Atlantic Ocean`.

![2020042322310200-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/3299161/80152190-25eab380-85b3-11ea-951b-37864e313da1.jpg)

2. `Log sofa` in the database is now called `Log chair`? At least, the image is the same and `Log chair` is missing from the database.

![2020042322180000-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/3299161/80152330-5df1f680-85b3-11ea-9f3c-514ca9a8c5a5.jpg)

3. The database has entries for `Mum wreath` and `Mum weath`. I think these refer to the same item.

Thanks for the great resource!

**Comment by jefflomacy** [comment]
It appears these three have been addressed. Can you confirm?

**Comment by celynwalters** [comment]
Looks good to me!
I'm assuming it was intentional to change the name to "Log Chair", but keep the id as "log-sofa".

**Comment by jefflomacy** [comment]
Yep. That way the item doesn't vanish from any user lists if we ever fully purge the site cache. We do not use numerical IDs, the IDs in the JSON are mapped all the way into user lists.
