### ISSUE TITLE
List Export/Import

### ISSUE THREAD

**Issue by jefflomacy** [jefflomacy/villagerdb#177]
Allow users to download their lists and send them to other people for import.

**Comment by jefflomacy** [comment]
On export, need two forms: human-readable (checked and default behavior), and one that is actually useful for import into the site.

**Comment by AaronMT** [comment]
I was looking around to do this tonight, I'd settle just to have a flat listing extracted from the JSON

**Comment by EhsanKia** [comment]
Let me know if I can help in any way. Would like to see integration with [@CatalogScanner](https://twitter.com/CatalogScanner), which output looks like this: https://ehsan.lol/M5BzdrDnGGd

**Comment by EhsanKia** [comment]
I think the following format above can be both human readable and parsable. Parsing should of course be case insensitive. By default, it sets unspecified variations to "any", but for specifying variations, I suggest:

```
item name [variation 1]
item name [variation 2]
```

Which each variation on a new line.

**Comment by jefflomacy** [comment]
This has largely been deployed already through CatalogScanner which is our preferred method of importing lists. Closing.
