### ISSUE TITLE
Feature Request: Add the ability to rename a list

### ISSUE THREAD

**Issue by nfraker** [jefflomacy/villagerdb#182]
> As a VillagerDB user, I would like to rename the lists I've created to better reflect changes to the purpose of my lists without having to recreate them from scratch.

Hope this is your preferred location for these sorts of things, and you're okay with the "user story" approach. Please let me know if there any any changes you'd like for me to make!

**Comment by jefflomacy** [comment]
This is already implemented. Click on the pen icon next to your list name. Let us know if it is not working. I will leave this ticket open until you confirm for me that it is working for you!

**Comment by jefflomacy** [comment]
This was renamed this morning. I'm going to close the ticket but please re-open it if this feature is not working for you.
