### ISSUE TITLE
Sort ordering of lists conflicts with the in game sort ordering

### ISSUE THREAD

**Issue by cecilkilmer** [jefflomacy/villagerdb#184]
The sort ordering of items in the site is different from in game, which is annoying when trying to compare to find items needed to update lists for catalog.

For example, wallpaper in the website lists "Blue-crown wall" after "Blue Subway-tile wall".  In game however, "Blue-crown wall" follows "Blue blossoming wall".  The game treats hyphens as spaces for alphabetical sort ordering, but the website treats it as a unique character that falls after space.

While having the display name with spaces is good to match the game, fixing the sort ordering to match the game and treat hyphens as spaces would be greatly appreciated!

**Comment by jefflomacy** [comment]
Hey! A fix is coming for this very soon, and it will be bundled in with a new list comparator feature. Tell me, though: is this issue resolved for you when using the actual category browser? Want to make sure we for sure resolved it there. Thanks for the info, and I'll update this ticket when the new feature is deployed and ask for your confirmation that the issue is fixed.

**Comment by cecilkilmer** [comment]
Yep, the ordering looks correct when browsing by category, just not within lists.  Glad to hear a fix is coming for this soon!  Wallpapers always take me extra long to go through and update because I keep jumping around my list in several places :)

**Comment by jefflomacy** [comment]
Since a build is coming tomorrow that directly impacts lists, I think I will prioritize fixing this tonight. Can you link me to your list that has this issue or provide a sample list so I can be sure I'm addressing it correctly?

**Comment by cecilkilmer** [comment]
https://villagerdb.com/user/cecilkilmer/list/wallpaper

Using the same example above, Blue-crown wall should follow "Blue blossoming wall", rather than "Blue Subway-tile wall"

**Comment by jefflomacy** [comment]
Thanks. Will (attempt to) address in the build going out tomorrow morning.

**Comment by jefflomacy** [comment]
This should be resolved. Please re-open the ticket if it is not.

**Comment by cecilkilmer** [comment]
Looks good, thank you!

**Comment by cecilkilmer** [comment]
Actually, I found a sort order problem with the new update (not sure if it was introduced by the update, or was there previously).  I'll open a new ticket since I can't figure out how to re-open this one.
