### ISSUE TITLE
Item Images

### ISSUE THREAD

**Issue by noahmarshall12** [jefflomacy/villagerdb#187]
Where would I be able to download images for all of the listed items (or the ones that have an image)?

**Comment by jefflomacy** [comment]
The most accessible way at this time is using the Data Source spreadsheet that has been going around for this game: https://docs.google.com/spreadsheets/d/13d_LAJPlxMa_DubPTuirkIV4DERBMXbrWQsmSh8ReK4/edit

The images in this spreadsheet are hosted on ACNHCDN: https://acnhcdn.com/

As this is not a service we provide ourselves, I am going to close this ticket but hope this is helpful to you.
