### ISSUE TITLE
'permission denied' occur in linux docker environment when exec command "sudo docker exec villagerdb_app npm run build-js""

### ISSUE THREAD

**Issue by alexzhu0592** [jefflomacy/villagerdb#230]
docker in linux environment , deploy the application by docker-compose and it is work,
however when execute command  "sudo docker exec villagerdb_app npm run build-js", error occurs , show this :
`

> Error: EACCES: permission denied, mkdir '/usr/src/app/public/jav...

`

i fix the problem by change execute command  "sudo docker exec villagerdb_app npm run build-js" to "sudo docker exec -u root villagerdb_app npm run build-js"

**Comment by trundleroo** [comment]
Closing this as you fixed it for your local but it doesn't really apply to all machines.
