### ISSUE TITLE
Unable to build search index

### ISSUE THREAD

**Issue by brogers5** [jefflomacy/villagerdb#256]
I'm trying to set up a self-hosted instance of VillagerDB to integration test some data changes I'd like to submit a PR for. In following the directions documented in the wiki's [Set Up a Development Environment](https://github.com/jefflomacy/villagerdb/wiki/Set-Up-a-Development-Environment) page, I'm struggling with getting a reindex operation working.

`docker exec villagerdb_app bin/util build-redis-db` works without an issue (assuming I clone the repository with `core.autocrlf` configured as `input`, but out-of-scope for this issue), but `build-search-index` consistently fails as follows:

> PS D:\Repositories\Git\villagerdb> docker exec villagerdb_app bin/util build-search-index
> Elasticsearch ERROR: 2020-06-13T00:08:06Z
>   Error: Request error, retrying
>   PUT http://villagerdb_es:9200/i1592006885277 => getaddrinfo ENOTFOUND villagerdb_es villagerdb_es:9200
>       at Log.error (/usr/src/app/node_modules/elasticsearch/src/lib/log.js:239:56)
>       at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:298:18)
>       at HttpConnector.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:171:7)
>       at ClientRequest.wrapper (/usr/src/app/node_modules/lodash/lodash.js:4929:19)
>       at ClientRequest.emit (events.js:198:13)
>       at Socket.socketErrorListener (_http_client.js:401:9)
>       at Socket.emit (events.js:198:13)
>       at emitErrorNT (internal/streams/destroy.js:91:8)
>       at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>       at process._tickCallback (internal/process/next_tick.js:63:19)
> 
> Elasticsearch WARNING: 2020-06-13T00:08:09Z
>   Unable to revive connection: http://villagerdb_es:9200/
> 
> Elasticsearch WARNING: 2020-06-13T00:08:09Z
>   No living connections
> 
> Failed to build search index.
> { Error: No Living connections
>     at sendReqWithConnection (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:266:15)
>     at next (/usr/src/app/node_modules/elasticsearch/src/lib/connection_pool.js:243:7)
>     at process._tickCallback (internal/process/next_tick.js:61:11)
>   message: 'No Living connections',
>   body: undefined,
>   status: undefined }

I'm running this from an elevated PowerShell 7.0.1 instance on Windows 10 Pro v2004. My Docker Desktop installation (v2.3.0.3) should be configured to use Linux containers.

I've noticed the `villagerdb_es` container in particular keeps restarting on its own, which I suspect may be contributing to this behavior. Any pointers for further troubleshooting would be much appreciated.

**Comment by brogers5** [comment]
Figured this one out after some further research. In looking at the [villagerdb_es](url) container's logs, this jumped out at me:

> ERROR: [1] bootstrap checks failed
> [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
> ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/villagerdb-es-cluster.log}

Fixed as follows, from an elevated PowerShell session:
> wsl -d docker-desktop
> sysctl -w vm.max_map_count=262144

For the devs, I'd recommend adding this to the wiki page. Unfortunately, I can't edit the wiki page myself, nor can I submit a direct PR for it.

**Comment by trundleroo** [comment]
Hey, we both ran into this issue while building this product but completely forgot to add it. I have added it to the wiki for setup. Thanks for raising this issue!

**Comment by brogers5** [comment]
Wanted to add another caveat for future readers: the `sysctl` command above is temporary and will not persist beyond the current operating system session. Permanently setting this will require editing a config file.

From [ElasticSearch's setup documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html):
> To set this value permanently, update the `vm.max_map_count` setting in `/etc/sysctl.conf`. To verify after rebooting, run `sysctl vm.max_map_count`.
