### ISSUE TITLE
Feature Request: add a quantity option to items

### ISSUE THREAD

**Issue by smashism** [jefflomacy/villagerdb#263]
Hello! Thank you so much for this great site that so many people use and enjoy (and rely on in the community). 

A very helpful feature for many would be the ability to add a quantity to items in inventory. That way if someone has 2 inflatable sofas, for example, that could be denoted on a list. It would be helpful for tracking and trading purposes.

Thanks!

**Comment by jefflomacy** [comment]
This was deployed this morning. You can add any text you wish to list items.
