### ISSUE TITLE
New list-item-updater is huge; option to hide?

### ISSUE THREAD

**Issue by asedeno** [jefflomacy/villagerdb#292]
My use case for the villagerdb catalog does not currently include attaching text to items. This new feature is now using two-thirds of the vertical real-estate of my screen when I'm browsing/updating my own lists. I could imagine wanting to use this feature in the future, but right now, I would like to be able to hide those elements and get back to looking at my own lists without them.

For myself, I've written some userscript to inject css to hide `.list-item.updater`, which will do for now, but it'd be better if it was available to everyone, perhaps with a default from an account preference.

Thanks for all the effort put into villagerdb!

**Comment by jefflomacy** [comment]
I am planning on adding an "update your profile" section soon and we can make this a configurable option, I see no problem with that. I will mark this ticket as an action item for this to be a preference on user profiles.

**Comment by jefflomacy** [comment]
I am also contemplating making it auto-update when the user stops typing, to cut down on some of the used space.

**Comment by jefflomacy** [comment]
Here’s a preview of what I can do quickly (tomorrow morning - it can auto update when the user finishes typing or pressed enter).

![E46B6A67-7A05-4822-82B9-97363A0B1F38](https://user-images.githubusercontent.com/57078432/96005077-1a61a200-0e0a-11eb-8b65-25e9f752302d.jpeg)

**Comment by jefflomacy** [comment]
I prioritized updating this and pushed an update tonight. Can you check this out and see if it's a good compromise? They are now hidden by default. I think this is a good compromise and prevents confusion with a future preference setting. Open to thoughts.

**Comment by asedeno** [comment]
I love it!

**Comment by jefflomacy** [comment]
Glad to hear it! Going to close this, we may make minor intuitive adjustments to this later but hidden will always remain the default now.
