### ISSUE TITLE
Feature Request: Add Notes to Lists

### ISSUE THREAD

**Issue by pronoiac** [jefflomacy/villagerdb#307]
While I can add notes to items in a list, I can't add, for example, "last updated 2020-12-13" to the list itself. (I know #211 covers that specific case.) Another use case: a brief explanation about *why* I'm gathering all these wreath DIYs.

**Comment by trundleroo** [comment]
Closes open merge of #314

**Comment by jefflomacy** [comment]
This was deployed this morning.
