### ISSUE TITLE
The database lacks "seasonal" and "geographic" information

### ISSUE THREAD

**Issue by xiaohuoni** [jefflomacy/villagerdb#74]
The database lacks "seasonal" and "geographic" information

**Comment by jefflomacy** [comment]
Critterpedia is the first thing we want to import from the new game. We are actively working on this but there is tooling we have to get done for the game in general. Will update ticket when this is published, hopefully by end of week.

**Comment by trundleroo** [comment]
Closing as this has been implemented for bugs and fish via "Where to get" data point.
