### ISSUE TITLE
Sorting lists in alphabetical order

### ISSUE THREAD

**Issue by MateosOTI** [jefflomacy/villagerdb#86]
Having the option to order your list in alphabetical order without doing it manually. Also, when adding new items to a list it would be good if they added in alphabetical order by default and not to the end of the list. This would make matching your catalog easier.

**Comment by jefflomacy** [comment]
Agreed, I actually have a branch that does this but I have not pushed it up yet. We will soon when we get a period to do another build.

**Comment by jefflomacy** [comment]
This has been deployed. Thank you for the ticket. Please re-open if you run into trouble with this feature.
