### ISSUE TITLE
Villagers with unknown birthdays should not display "Unknown"

### ISSUE THREAD

**Issue by trundleroo** [jefflomacy/villagerdb#9]
Currently, villagers with no known birthday has "unknown" fields in their profile. This occurs in both the auto generated paragraph and the birthday/zodiac field. 

Some villagers that don't appear in games after AFE+ seemingly should not have birthdays in the first place. This data should be looked into and corrected if necessary.

**Comment by jefflomacy** [comment]
This was fixed in a recent deployment. Closing.
