### ISSUE TITLE
How should this be licensed?

### ISSUE THREAD

**Issue by nickmccurdy** [jefflomacy/villagerdb#98]
Hi, I'm working on a tool that relies on item data, and this seems like a useful resource. However, I don't see any license on the code or data, which implies that all rights are reserved, and would prevent derivative works.

Would you mind considering an open source or Creative Commons license? For what it's worth, most Node projects use permissive licenses like MIT or ISC. Creative Commons licenses are also often used for data, and allow additional restrictions like noncommercial use.

**Comment by trundleroo** [comment]
The data is public domain and the code is GPLv3. You are welcome to use the data for projects you are working on.
